### ISSUE TITLE
distributed knowledge

### ISSUE THREAD

**Issue by m4lvin** [jrclogic/SMCDEL#24]
[Distributed knowledge](https://plato.stanford.edu/entries/dynamic-epistemic/#DistKnow) is currently not expressible.

1. A `D :: [Agent] -> Form -> Form` operator to say "It is distributed knowledge among ... that ..." should be added in `SMCDEL.Language` and the lexer and parser.

2. Semantics for it need to be defined in at least the four main modules:
    - [ ] Explicit.S5
    - [ ] Explicit.K
    - [ ] Symbolic.S5
    - [ ] Symbolic.K

Side note: a more radical alternative might be to move completely to a PDL-style structure of epistemic modalities as done in "Logics of communication and change" https://doi.org/10.1016/j.ic.2006.04.006

**Comment by foxyseta** [comment]
Hi! Should the development branch be based on `master` or `next`?

**Comment by m4lvin** [comment]
Thanks for asking. Indeed it is better if you work on top of the `next` branch.

**Comment by m4lvin** [comment]
Done since https://github.com/jrclogic/SMCDEL/pull/36
